#include "web_server.h"
#include <stdlib.h>
#include <string.h>
#include "app_config.h"
#include "sensor_manager.h"
#include "network.h"
#include "cJSON.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_check.h"
#include "esp_system.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
extern const unsigned char index_html_start[] asm("_binary_index_html_start");extern const unsigned char index_html_end[] asm("_binary_index_html_end");
static const char*TAG="web";
static esp_err_t json_send(httpd_req_t*r,cJSON*j){char*s=cJSON_PrintUnformatted(j);httpd_resp_set_type(r,"application/json");httpd_resp_set_hdr(r,"Cache-Control","no-store");esp_err_t e=httpd_resp_sendstr(r,s);free(s);cJSON_Delete(j);return e;}
static cJSON *reading_json(int i){sensor_reading_t s;sensor_manager_get(i,&s);cJSON*j=cJSON_CreateObject();cJSON_AddNumberToObject(j,"channel",i+1);cJSON_AddBoolToObject(j,"online",s.online);cJSON_AddStringToObject(j,"configuredType",sensor_type_name(s.configured));cJSON_AddStringToObject(j,"detectedFamily",sensor_family_name(s.family));if(s.serial[0])cJSON_AddStringToObject(j,"serialNumber",s.serial);else cJSON_AddNullToObject(j,"serialNumber");if(s.online){cJSON_AddNumberToObject(j,"rawTemperature",s.raw_temperature);cJSON_AddNumberToObject(j,"rawHumidity",s.raw_humidity);cJSON_AddNumberToObject(j,"temperature",s.temperature);cJSON_AddNumberToObject(j,"humidity",s.humidity);}else{cJSON_AddNullToObject(j,"rawTemperature");cJSON_AddNullToObject(j,"rawHumidity");cJSON_AddNullToObject(j,"temperature");cJSON_AddNullToObject(j,"humidity");}cJSON_AddNumberToObject(j,"lastReadMs",s.last_read_ms);cJSON_AddNumberToObject(j,"errorCount",s.error_count);cJSON_AddNumberToObject(j,"sampleCount",s.sample_count);return j;}
static esp_err_t index_get(httpd_req_t*r){httpd_resp_set_type(r,"text/html");return httpd_resp_send(r,(const char*)index_html_start,index_html_end-index_html_start);}
static esp_err_t sensors_get(httpd_req_t*r){cJSON*a=cJSON_CreateArray();for(int i=0;i<8;i++)cJSON_AddItemToArray(a,reading_json(i));return json_send(r,a);}
static esp_err_t sensor_get(httpd_req_t*r){const char*p=strrchr(r->uri,'/');int ch=p?atoi(p+1):0;if(ch<1||ch>8){httpd_resp_send_err(r,HTTPD_404_NOT_FOUND,"channel must be 1-8");return ESP_OK;}return json_send(r,reading_json(ch-1));}
static esp_err_t status_get(httpd_req_t*r){cJSON*j=cJSON_CreateObject();cJSON_AddStringToObject(j,"firmwareVersion",APP_VERSION);cJSON_AddNumberToObject(j,"uptimeSeconds",esp_timer_get_time()/1000000);cJSON_AddNumberToObject(j,"wifiRssi",network_rssi());cJSON_AddStringToObject(j,"networkMode",network_mode());return json_send(r,j);}
static cJSON *config_json(void){app_config_t c;app_config_get(&c);cJSON*j=cJSON_CreateObject(),*n=cJSON_AddObjectToObject(j,"network"),*a=cJSON_AddArrayToObject(j,"channels");cJSON_AddBoolToObject(n,"dhcp",c.dhcp);cJSON_AddStringToObject(n,"ssid",c.ssid);cJSON_AddStringToObject(n,"ip",c.ip);cJSON_AddStringToObject(n,"gateway",c.gateway);cJSON_AddStringToObject(n,"netmask",c.netmask);cJSON_AddStringToObject(n,"dns",c.dns);for(int i=0;i<8;i++){cJSON*x=cJSON_CreateObject();cJSON_AddNumberToObject(x,"channel",i+1);cJSON_AddStringToObject(x,"type",sensor_type_name(c.channels[i].type));cJSON_AddNumberToObject(x,"temperatureOffset",c.channels[i].temp_offset);cJSON_AddNumberToObject(x,"humidityOffset",c.channels[i].humidity_offset);cJSON_AddItemToArray(a,x);}return j;}
static esp_err_t config_get(httpd_req_t*r){return json_send(r,config_json());}
static cJSON *body(httpd_req_t*r){if(r->content_len<=0||r->content_len>4096)return NULL;char*b=malloc(r->content_len+1);if(!b)return NULL;int n=httpd_req_recv(r,b,r->content_len);if(n<=0){free(b);return NULL;}b[n]=0;cJSON*j=cJSON_Parse(b);free(b);return j;}
static void copystr(cJSON*j,const char*k,char*d,size_t n){cJSON*x=cJSON_GetObjectItemCaseSensitive(j,k);if(cJSON_IsString(x)){strncpy(d,x->valuestring,n-1);d[n-1]=0;}}
static esp_err_t network_put(httpd_req_t*r){cJSON*j=body(r);if(!j){httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"invalid JSON");return ESP_OK;}app_config_t c;app_config_get(&c);cJSON*x=cJSON_GetObjectItem(j,"dhcp");if(cJSON_IsBool(x))c.dhcp=cJSON_IsTrue(x);copystr(j,"ssid",c.ssid,sizeof(c.ssid));x=cJSON_GetObjectItemCaseSensitive(j,"password");if(cJSON_IsString(x)&&x->valuestring[0])copystr(j,"password",c.password,sizeof(c.password));copystr(j,"ip",c.ip,sizeof(c.ip));copystr(j,"gateway",c.gateway,sizeof(c.gateway));copystr(j,"netmask",c.netmask,sizeof(c.netmask));copystr(j,"dns",c.dns,sizeof(c.dns));cJSON_Delete(j);esp_err_t e=app_config_save(&c);if(e){httpd_resp_send_err(r,HTTPD_500_INTERNAL_SERVER_ERROR,"NVS write failed");return ESP_OK;}cJSON*o=cJSON_CreateObject();cJSON_AddBoolToObject(o,"ok",true);cJSON_AddBoolToObject(o,"rebootRequired",true);return json_send(r,o);}
static esp_err_t channels_put(httpd_req_t*r){cJSON*j=body(r);cJSON*a=cJSON_IsArray(j)?j:cJSON_GetObjectItem(j,"channels");if(!cJSON_IsArray(a)){cJSON_Delete(j);httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"expected channels array");return ESP_OK;}app_config_t c;app_config_get(&c);cJSON*x=NULL;cJSON_ArrayForEach(x,a){cJSON*cn=cJSON_GetObjectItem(x,"channel"),*ty=cJSON_GetObjectItem(x,"type"),*to=cJSON_GetObjectItem(x,"temperatureOffset"),*ho=cJSON_GetObjectItem(x,"humidityOffset");if(!cJSON_IsNumber(cn)||cn->valueint<1||cn->valueint>8||!cJSON_IsString(ty))continue;int i=cn->valueint-1;c.channels[i].type=sensor_type_parse(ty->valuestring);if(cJSON_IsNumber(to))c.channels[i].temp_offset=to->valuedouble;if(cJSON_IsNumber(ho))c.channels[i].humidity_offset=ho->valuedouble;}cJSON_Delete(j);app_config_save(&c);sensor_manager_detect();return json_send(r,config_json());}
static esp_err_t action(httpd_req_t*r){if(strstr(r->uri,"detect")){sensor_manager_detect();httpd_resp_sendstr(r,"{\"ok\":true}");}else if(strstr(r->uri,"factory-reset")){app_config_factory_reset();httpd_resp_sendstr(r,"{\"ok\":true,\"rebooting\":true}");vTaskDelay(pdMS_TO_TICKS(200));esp_restart();}else{httpd_resp_sendstr(r,"{\"ok\":true,\"rebooting\":true}");vTaskDelay(pdMS_TO_TICKS(200));esp_restart();}return ESP_OK;}
esp_err_t web_server_start(void){httpd_config_t c=HTTPD_DEFAULT_CONFIG();c.max_uri_handlers=12;c.uri_match_fn=httpd_uri_match_wildcard;httpd_handle_t h;ESP_RETURN_ON_ERROR(httpd_start(&h,&c),TAG,"start");httpd_uri_t u[]={ {.uri="/",.method=HTTP_GET,.handler=index_get},{.uri="/api/v1/sensors",.method=HTTP_GET,.handler=sensors_get},{.uri="/api/v1/sensors/*",.method=HTTP_GET,.handler=sensor_get},{.uri="/api/v1/status",.method=HTTP_GET,.handler=status_get},{.uri="/api/v1/config",.method=HTTP_GET,.handler=config_get},{.uri="/api/v1/config/network",.method=HTTP_PUT,.handler=network_put},{.uri="/api/v1/config/channels",.method=HTTP_PUT,.handler=channels_put},{.uri="/api/v1/sensors/detect",.method=HTTP_POST,.handler=action},{.uri="/api/v1/reboot",.method=HTTP_POST,.handler=action},{.uri="/api/v1/factory-reset",.method=HTTP_POST,.handler=action}};for(size_t i=0;i<sizeof(u)/sizeof(u[0]);i++)ESP_ERROR_CHECK(httpd_register_uri_handler(h,&u[i]));return ESP_OK;}
